name: release

on:
  push:
    branches: [main]
    paths:
      - "**.go"
      - "go.mod"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8 # 1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          TAG_PREFIX: v

      - uses: cli/gh-extension-precompile@9e2237c30f869ad3bcaed6a4be2cd43564dd421b # v2.1.0
        with:
          go_version_file: go.mod
          go_build_options: ./cmd/podfails
          release_tag: ${{ steps.tag.outputs.new_tag }}
